# Clojure CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 699b6b14016c608aba40eede27b18b2f5857f39f0ad580b81c6cb01d18c169e7
    docker:
      - image: circleci/openjdk:8u222-jdk

    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run:
          name: Run Tests
          command: |
            mvn test
      - run:
          name: Upload Test Coverage
          command: |
            ./tmp/cc-test-reporter upload-coverage -i target/jacoco.exec