= Digger : User Guide
Hildeberto Mendonca <me@hildeberto.com>
v0.4.0, 2019-10-14
:doctype: book
:encoding: utf-8
:toc: left
:toclevels: 4
:numbered:

Digger is designed to document existing databases. It is specially useful to document legacy databases, where the documentation is sparced and outdated.

[#datasource]
== Datasource

Datasource is a reference to an existing database that we intend to document. A datasource has enough information to connect to the database and extract metadata information.

[#new_datasource]
=== Creating a New Datasource

[#edit_datasource]
=== Editing a Datasource

[#table]
== Table

Table is a tabular structure used to store, organize and retrieve data. It can be a database table, a temporary table, a view, and other vendor specific alternatives.

[#new_table]
=== Documenting a Table

[#edit_table]
=== Editing the Documentation of a Table

[#ignored_table]
== Ignored Table

[#new_ignored_table]
=== Ignoring a Table

[#remove_ignored_table]
=== Removing a Table from the Ignored List

[#column]
== Column

[#new_column]
=== Documenting a Table Column

[#edit_column]
=== Editing the Documentation of a Column